"""destination table

Revision ID: bc28256342e5
Revises: 
Create Date: 2019-10-10 10:45:06.506628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc28256342e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=500), nullable=False),
    sa.Column('country_name', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=6), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destination')
    # ### end Alembic commands ###
